services:
  # listens to mqtt packets and saves to database
  meshtastic-map-mqtt:
    container_name: meshtastic-map-mqtt
    build:
      context: mqtt
      dockerfile: Dockerfile.dev
    depends_on:
      database:
        condition: service_healthy
    environment:
      DATABASE_URL: "mysql://root:password@database:3306/meshtastic-map?connection_limit=100"
    volumes:
      - ./mqtt:/app
      - /app/node_modules

  # runs the database to store everything from mqtt
  database:
    container_name: database
    image: bitnami/mariadb
    ports:
      - 3306:3306/tcp
    environment:
      MARIADB_DATABASE: "meshtastic-map"
      MARIADB_ROOT_PASSWORD: "password"
    volumes:
      - database_data:/bitnami/mariadb
    healthcheck:
      test: ["CMD", "/opt/bitnami/scripts/mariadb/healthcheck.sh"]
      interval: 15s
      timeout: 5s
      retries: 6
      start_interval: 5s

volumes:
  database_data:
