services:

  # listens to mqtt packets and saves to database
  meshtastic-map-api:
    container_name: meshtastic-map-api
    build:
      context: api
      dockerfile: Dockerfile.dev
    env_file:
      - .env
    volumes:
      - ./api:/app
      - /app/node_modules