name: build

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build APP
        uses: docker/build-push-action@v6
        with:
          context: "{{defaultContext}}"
          file: ./app/Dockerfile

      - name: Build API
        uses: docker/build-push-action@v6
        with:
          context: "{{defaultContext}}"
          file: ./api/Dockerfile

      - name: Build MQTT
        uses: docker/build-push-action@v6
        with:
          context: "{{defaultContext}}"
          file: ./mqtt/Dockerfile
