name: build

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to DockerHub
        if: github.ref == 'refs/heads/main'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
      - name: Build and push APP Docker image
        uses: docker/build-push-action@v6
        with:
          context: "{{defaultContext}}"
          file: ./app/Dockerfile
          push: ${{ github.ref == 'refs/heads/main' }}
          tags: komelt/meshtastic-map:latest

      - name: Build and push API Docker image
        uses: docker/build-push-action@v6
        with:
          context: "{{defaultContext}}"
          file: ./api/Dockerfile
          push: ${{ github.ref == 'refs/heads/main' }}
          tags: komelt/meshtastic-map-api:latest
          
      - name: Build and push MQTT Docker image
        uses: docker/build-push-action@v6
        with:
          context: "{{defaultContext}}"
          file: ./mqtt/Dockerfile
          push: ${{ github.ref == 'refs/heads/main' }}
          tags: komelt/meshtastic-map-mqtt:latest