name: build-push

on:
  push:
    branches:
      - main

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push APP
        uses: docker/build-push-action@v6
        with:
          context: "{{defaultContext}}"
          push: true
          file: "./app/Dockerfile"
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/meshtastic-map:latest

      - name: Build and push API
        uses: docker/build-push-action@v6
        with:
          context: "{{defaultContext}}"
          push: true
          file: "./api/Dockerfile"
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/meshtastic-map-api:latest

      - name: Build and push MQTT listener
        uses: docker/build-push-action@v6
        with:
          context: "{{defaultContext}}"
          push: true
          file: "./mqtt/Dockerfile"
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/meshtastic-map-mqtt:latest
